---
title: "DAGs"
author: "Laura Dee"
editor: visual
---

## Resources of creating and analyzing Directed Acyclic Graphs

## Useful Videos

#### Conceptual

-   Discussion of how to identify associations, close backdoors, and isolate pathways in a DAG by A. Heiss: <https://www.youtube.com/watch?v=_qs_1B4ySWY>

-   Watch Hernan video: "3. Elements of DAGs"

#### Implementation

-   How to build and begin to analyze them it in ggdag by A. Heiss: <https://www.youtube.com/watch?v=uoAjyyToUTE>

-   Drawing DAGs with Daggit.net by A. Heiss: https://www.youtube.com/watch?v=3euqrnD9w7c

-   Intro to DAGitty for identifying confounding variables: <https://www.youtube.com/watch?v=sI_w9uVLdCg>

## Software for DAG construction and analysis

a\) [Daggitity](https://www.dagitty.net)

b\) [ggdag](https://cran.r-project.org/web/packages/ggdag/vignettes/intro-to-ggdag.html) is a nice R package based on dagitty but in R tidyverse-compatible and with much better plotting functionality\
c) [shinydag](https://www.gerkelab.com/project/shinydag/) is another GUI aimed at visualizing DAGs and exporting them in different publication-ready formats\
d) [TETRAD](https://sites.google.com/view/tetradcausal)\
e) [DAG program](https://hsz.dife.de/dag/)\
f) [dagR](https://journals.lww.com/epidem/Fulltext/2010/07000/dagR__A_Suite_of_R_Functions_for_Directed_Acyclic.26.aspx)

### Key Messages - well said in Cunningham (2021) Ch. 3:

*Well summarized fom Cunningham (2021) Ch. 3:* "Causal effects can happen in two ways. They can either be direct (e.g., D→Y), or they can be mediated by a third variable (e.g., D→X→Y). When they are mediated by a third variable, we are capturing a sequence of events originating with D, which may or may not be important to you depending on the question you’re asking.

A DAG is meant to describe all causal relationships relevant to the effect of D on Y. What makes the DAG distinctive is both the explicit commitment to a causal effect pathway and the complete commitment to the *lack of* a causal pathway represented by missing arrows. In other words, a DAG will contain both arrows connecting variables and choices to exclude arrows. And the lack of an arrow necessarily means that you think there is no such relationship in the data—this is one of the strongest beliefs you can hold. A complete DAG will have all direct causal effects among the variables in the graph as well as all common causes of any pair of variables in the graph.

At this point, you may be wondering where the DAG comes from. It’s an excellent question. It may be *the* question. A DAG is supposed to be a theoretical representation of the state-of-the-art knowledge about the phenomena you’re studying. It’s what an expert would say is the thing itself, and that expertise comes from a variety of sources. Examples include economic theory, other scientific models, conversations with experts, your own observations and experiences, literature reviews, as well as your own intuition and hypotheses....

.... I have found DAGs to be useful for understanding the critical role that prior knowledge plays in identifying causal effects. But there are other reasons too. One, I have found that DAGs are very helpful for communicating research designs and estimators if for no other reason than pictures speak a thousand words.....

..... Two, through concepts such as the backdoor criterion and collider bias, a well-designed DAG can help you develop a credible research design for identifying the causal effects of some intervention. As a bonus, I also think a DAG provides a bridge between various empirical schools, such as the structural and reduced form groups. And finally, DAGs drive home the point that assumptions are necessary for any and all identification of causal effects, which economists have been hammering at for years ([Wolpin 2013](https://mixtape.scunning.com/references#ref-Wolpin2013))."

#### Additional Background Readings

For additional background on DAGs:

-   Morgan & Winship (2007) pgs. 29-34 and Ch. 3 (see GDrive)
-   [Cunningham (2021) Ch. 3](https://mixtape.scunning.com/03-directed_acyclical_graphs)
-   Heiss, A. [Do-calculus adventures! Exploring the three rules of do-calculus in plain language and deriving the backdoor adjustment formula by hand](https://www.andrewheiss.com/blog/2021/09/07/do-calculus-backdoors/#exploring-the-rules-of-do-calculus)
