---
title: "Readings by Class & Additional Materials"
---

Note: book chapters can be found on the private [course Google Drive](https://drive.google.com/drive/folders/1YjydIdJ6GAD2MTzYdlUote46PJ-rCwvp?usp=share_link), as well as pdfs of the papers. Demos will be in RMarkdown and on the [course GitHub page in the exercises folder](https://github.com/LauraDee/EcologyCausalInference).

## Due Mon. 8/24 - Intro

First class; Complete [pre-course survey](https://forms.gle/cv7dr13eRB4xe5E87) in class; Review Syllabus and website

## Due Wed. 8/26 - Causal claims and aims

1)  [Hernan et al. 2019](https://doi.org/10.1080/09332480.2019.1579578)
2)  [Laubach et al. 2021](https://doi.org/10.1098/rspb.2020.2815)
3)  [Mixtape 4.1: Traditional Prediction versus Causal Inference](https://mixtape.scunning.com/04-potential_outcomes_and_randomization)
4)  Angrist & Pischke 2008, Chapter 1 (from *Mostly Harmless Econometrics*)

## Due Mon. 8/31 - Structural Causal Model and Directed Acyclic Graphs (DAG)

1)  [Arif & MacNeil 2022](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecm.1554)
2)  [Rohrer 2018](https://journals.sagepub.com/doi/epub/10.1177/2515245917745629)

Guest speaker: Dr. Zach Laubach

Optional, additional useful background reading on DAGs:\
3) [Borger and Ramesh 2025](https://doi.org/10.1098/rspb.2025.0963) 4\
4) Morgan & Winship (2007) pgs. 29-34 and Ch. 3\
5) [The Effect Ch. 6](https://theeffectbook.net/ch-CausalDiagrams.html)

6\) [Cunningham (2021) Ch. 3](https://mixtape.scunning.com/03-directed_acyclical_graphs)

## Due Wed. 9/2 - Potential Outcomes

1)  Angrist & Pischke 2008, Chapter 2 (from *Mostly Harmless Econometrics*)
2)  [Mixtape: 4.2 Potential Outcomes](https://mixtape.scunning.com/04-potential_outcomes_and_randomization#potential-outcomes)

Optional: Morgan & Winship Book, Ch. 2

## Due Mon. 9/7 Labor Day: No Class

## Due Wed. 9/9 - Experiments and Randomization

1)  Gerber & Green, Chapter 1
2)  Gerber & Green, Chapter 2
3)  [Kimmel et al. 2021](https://pubmed.ncbi.nlm.nih.gov/34538502/)\

Optional: [Mixtape: 4.4 Randomization](https://mixtape.scunning.com/04-potential_outcomes_and_randomization#randomization)

## Due Mon. 9/14 Designing and Breaking Experiments: bias and solutions

1)  [Arif & Massey (2023) Reducing bias in experimental ecology through directed acyclic graphs](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.9947)
2)  [Mixtape: 4.5 SUTVA](https://mixtape.scunning.com/04-potential_outcomes_and_randomization#randomization)

Note: Please read [Kimmel et al. 2021](https://pubmed.ncbi.nlm.nih.gov/34538502/) if you didn't for last class

## Due Wed 9/16 Target Validity, External Validity, Transportability

TBD something on external validity: transportability, target validity,

## Due Mon. 9/21 Introduction to Challenges of Observational Data

1)  Watch Imbens video: [2022 Nobel Prize lecture](https://www.nobelprize.org/prizes/economic-sciences/2021/imbens/lecture/)
2)  [Larsen et al. 2019](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13190) - up to section 8, and the Discussion. *Can skim in between for preview of what's to come.*
3)  [Siegel & Dee (2025) Ecology Letters](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.70053) - *up until section 5.1.*

Optional and more advanced: Angrist & Pischke 2008, Chapter 3 (from *Mostly Harmless Econometrics*)

Optional:

\- [Ferraro 2009](https://doi.org/10.1002/ev.297)\
- [Ferraro and Hanauer 2014 Advances in Measuring the Environmental and Social Impacts of Environmental Programs](https://www.google.com/search?client=safari&rls=en&q=Ferraro+and+Hanauer+2014+Advances+in+Measuring+the+Environmental+and+Social+Impacts+of+Environmental+Programs&ie=UTF-8&oe=UTF-8)

## Due Wed. 9/23 - Workshop: Start your DAGs and get feedback

*FLIPPED CLASSROOM - Watch Dr. Suchinta Arif presentation prior to class and read:*

1\) [Vanderwheele 2019 Principles of confounder selection](https://doi.org/10.1007/s10654-019-00494-6)

2\) Review DAG resources and [DAG software](http://dagitty.net) on the website's [DAGs resources tab](https://lauradee.github.io/EcologyCausalInference/DAGs.html)

Prior to and during the class period, you will start your projects and make a first DAG. Review the DAG resources page tab on the website, and send Laura your DAG for feedback and dicussion with the class. *Be prepared to present and discuss your DAG.*

## Due Mon. 9/28 Matching and Weighting

1)  [Ramsey et al. 2018](https://doi.org/10.1111/2041-210X.13111)
2)  [Stuart 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2943670/)

Optional: -[Chesnaye et al. 2022](https://pubmed.ncbi.nlm.nih.gov/35035932/)\
-[McCaffery et al. 2013 A Tutorial on Propensity Score Estimation for Multiple Treatments Using Generalized Boosted Models](https://pmc.ncbi.nlm.nih.gov/articles/PMC3710547/)

## Due Wed. 9/30 \[Discussion lead(s): \]

1)  [Siegel et al. 2022](https://doi.org/10.1007/s10113-022-01950-y)
2)  [Xu et al. 2022](https://www.science.org/doi/10.1126/sciadv.abo0119)

*demo* RMarkdowns from Siegel & Dee (2025) Ecology Letters for weighting and matching on course GitHub [here](https://github.com/LauraDee/EcologyCausalInference/tree/main/exercises/Siegel_and_Dee_2025_Exercises_intro_causal_inf).

## Due Mon. 9/5 Difference-in-Difference

1)  Angrist & Pischke **2015**, Chapter 5 (note: this is in the book *Mastering ‘Metrics*)
2)  The Effect [Ch. 16 - Fixed Effects](https://theeffectbook.net/ch-FixedEffects.html) up until 16.2.2 Multiple Sets of Fixed Effects.
3)  The Effect [Ch. 18](https://theeffectbook.net/ch-DifferenceinDifference.html) up until 18.2.5 Rollout Designs and Multiple Treatment Periods.

## Due Wed. 10/7 \[Discussion lead(s): \]

*DUE Draft of Revised DAG OR literature review proposal (1 page max.)*\
1) [Simler-Williamson & Germino 2022](https://www.nature.com/articles/s41467-022-31102-z)\
2) The Effect [Ch. 18](https://theeffectbook.net/ch-DifferenceinDifference.html) starting at 18.2.5 Rollout Designs and Multiple Treatment Periods.

*demo* RMarkdown using Boulder Open Space fire and vegetation case on course GitHub (data in GoogleDrive)

Optional:

1\) [Roth et al. (2023). What's trending in difference in difference?](https://www.sciencedirect.com/science/article/abs/pii/S0304407623001318)

2\) Pedro Sant'Anna's DiD resources and [*Comprehensive Course on DiD*](https://psantanna.com/did-resources/)

3)[Bell et al. 2019. Fixed and random effects models making an informed choice](https://link.springer.com/article/10.1007/s11135-018-0802-x)

Fixed Effects Applications in Ecology for Discussion:

1\) [Dudney et al. 2021](https://www.nature.com/articles/s41467-021-25182-6) 

2\) [Dee et al., 2023](https://www.nature.com/articles/s41467-023-37194-5)

## Due Mon. 10/12 Panel methods continued; Two-way fixed effects

1\) Angrist & Pischke **2008**, Chapter 5\
2) The Effect [Ch. 16 - Fixed Effects](https://theeffectbook.net/ch-FixedEffects.html) starting at 16.2.2 Multiple Sets of Fixed Effects 3) [Brynes and Dee (2025) Ecology Letters](https://pubmed.ncbi.nlm.nih.gov/39836442/)

*demo* Brynes & Dee Rmarkdown on \[GitHub here\](https://github.com/jebyrnes/ovb_yeah_you_know_me/tree/v1.0.2)

Optional: [Bell et al. 2019. Fixed and random effects models making an informed choice](https://link.springer.com/article/10.1007/s11135-018-0802-x)\
*demo* Dee et al. Rmarkdown on course GitHub

## Due Wed. 10/14 - Synthetic Control

1)  [Fick et al (2020)](https://drive.google.com/file/d/1pCl1LkraGB7O55NsgW3j9lPVdBg9Tvar/view)
2)  [Kaiser, Resasco and Dee (2026)](https://www.nature.com/articles/s41559-026-03084-4)\

*Optional:* [The Effect section 21.2.1 Synthetic Control](https://theeffectbook.net/ch-TheEdge.html)\
For a more complete treatment of synthetic control, see: [Mixtape Ch. 10](https://mixtape.scunning.com/10-synthetic_control)

Other Applications:

\- [Wu et al. 2023](https://www.science.org/doi/epdf/10.1126/sciadv.adi4123)\
- [Lawson and Smith 2023](https://onlinelibrary.wiley.com/doi/10.1111/faf.12752)

## Due Mon. 10/19 Instrumental Variables

1)  Angrist & Pischke **2015**, Chapter 3 (note: this is in *Mastering ‘Metrics*)
2)  Kendall book chapter (in GDrive)

## Due Wed. 10/21 Instrumental Variables Applications \[Discussion lead(s): \]

1)  [Sims 2010](https://www.sciencedirect.com/science/article/pii/S0095069610000586)
2)  [MacDonald & Mordecai 2020](https://www.pnas.org/doi/10.1073/pnas.1905315116)

## Due Mon. 10/26 Regression Discontinuity Designs

1)  [The Effect Ch. 20](https://theeffectbook.net/ch-RegressionDiscontinuity.html)
2)  Siegel et al. preprint

Optional: Angrist & Pischke **2015**, Chapter 4 (note: this is in *Mastering ‘Metrics* in the GDrive)

*demo*

## Due Wed. 10/28 RDD Applications \[Discussion lead(s): \_\_\_\_\_\]

1)  [Englander 2019](https://doi.org/10.1038/s41893-019-0389-9)
2)  [Noack et al. 2022](https://doi.org/10.1111/ajae.12274)

Optional paper:

[Burgess et al. 2019](https://osf.io/preprints/socarxiv/67xg5/)

## Due Mon. 11/2 Comparison across designs; Robustness Checks and Sensitivity Tests

Revisit these papers in light of the assumptions of different designs, their different estimands, generalizability, and their assumptions: 

\- [Simler-Williamson & Germino 2022](https://www.nature.com/articles/s41467-022-31102-z)\
- [Dee et al., 2023](https://www.nature.com/articles/s41467-023-37194-5)\
- For Sensitivity Tests, see [sensemakr help](https://carloscinelli.com/sensemakr/) for a primer in R

Optional to revisit for methods comparisons:

1\) [Siegel & Dee (2025) Ecology Letters](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.70053)\
2) [Butsic et al. 2017](https://www.sciencedirect.com/science/article/pii/S1439179116301323)\
3) [Arif & MacNiel 2021 *Ecosphere*](https://esajournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ecs2.4009)

## Due Wed. 11/4 Project Day on Study Designs

Project work and discussions of design choices *DUE: In class - brief presentation on project* Come preparfe with a brief presentation (5 minutes) of your project: the "so what" big picture, the question you are addressing, its applications, your DAG and/or data context, and your proposed method for feedback and Q&A.

Please read the rest of these papers and come with a proposal for the statistical design you'll use and reasoning why:

[Siegel & Dee (2025) Ecology Letters](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.70053);\
[Larsen et al. 2019](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13190)

## Due Mon. 11/9 Power, standard error estimation, inference, and reproducibility \[Discussion lead(s): \]

1)  Read [The Effect: Chapter 13 "Your standard errors are probably wrong"](https://theeffectbook.net/ch-StatisticalAdjustment.html)
2)  Read [Kimmel, Avolio & Ferraro 2023](https://www.nature.com/articles/s41559-023-02144-3)

For a deeper dive on standard error estimation, read [Cameron and Miller. A pracitioner's guide to clustered robust standard errrors](https://cameron.econ.ucdavis.edu/research/Cameron_Miller_JHR_2015_February.pdf)

## Due Wed. 11/11 Heterogeneity and Generalizability

Read:

1\) [Spake et al. 2022](https://www.nature.com/articles/s41559-022-01891-z)

2\) [Spake et al. 2025](https://www.nature.com/articles/s41559-025-02733-4)

## Due Mon. 11/16 Mediation

Read [Correia et al. 2025](https://onlinelibrary.wiley.com/doi/10.1111/brv.70011)

*in class demo*

## Due Wed. 11/18 TBD

Special Topics Project (ML and causal) or Project check in and session

## Week of Nov. 23 (11/23 and 11/25): No Class

Thanksgiving Break - Work on your projects

## Due Mon. 11/30 Final Project Presentations - Group 1

## Due Wed. 12/2 Final Project Presentations - Group 2

*Project Presentations*

Guidelines for all presentations:

-   8 minute presentation + 2 minutes for questions\
-   Introduce the question you address and the motivation for your project

Specific guidelines for data analysis project presentations:

-   Describe the causal inference approach you took and why you chose that approach\

-   Present your DAG\

-   Briefly describe the data you used\

-   Share your results AND contextualize them with the important limitations and assumptions of the method(s) you used\

-   Outline possible next steps you could take to make your analysis more robust in the future\
    Specific guidelines for literature review presentations:

-   Describe the challenge for causal inference\

-   Describe and critique the current approaches people are taking\

-   Present your ideas for how the field could better incorporate causal inference methods

## Projects Due Sunday Dec 6th by email

See Assignments & Evaluation tab for more information

# Recommended Textbooks (not required)

I do not expect you to buy any/all of these books. I will provide the sections that are assigned for class. But if you want to explore topics of causal inference further, I recommend these books! Several are free online.

*Note: Some of these texts use examples to illustrate their points that are problematic (e.g., treating gender as a binary or studying post-colonial economic development without considering the violence of colonialism). We do not agree with the assumptions underlying these examples and we acknowledge the problems with them. The descriptions of methods are still some of the easiest to read out there.*

-   Huntinton-Klein, N. [*The Effect*](https://theeffectbook.net) free online
-   Morgan, SL and C Winship. 2007. [*Counterfactuals and Causal Inference: methods and principles for social research*](https://doi.org/10.1017/CBO9781107587991).\
-   Gerber, AS and DP Green. 2012. [*Field Experiments: design, analysis and interpretation*](https://wwnorton.com/books/9780393979954). (especially useful if you plan to do field experiments in your research)\
-   Cunningham, S. 2021. [*Causal Inference: The Mixtape*](https://mixtape.scunning.com/) (New Haven, CT: Yale University Press). [Available online for free](https://mixtape.scunning.com/)\
-   Angrist, JD and JS Pischke. 2015. [*Mastering ’Metrics: The Path from Cause to Effect*](https://www.masteringmetrics.com/) (Princeton, NJ: Princeton University Press).\
-   Angrist, JD and JS Pischke. 2008. [*Mostly Harmless Econometrics: an empiricist’s companion*](https://www.mostlyharmlesseconometrics.com/). (Princeton, NJ: Princeton University Press).\
-   Rosenbaum, P. 2010. [*Observational Studies*](https://doi.org/10.1007/978-1-4757-3692-2). Springer.\
-   Pearl, J. and D. Mackenzie. 2018. [*The Book of Why*](https://dl.acm.org/doi/10.5555/3238230). (New York, NY: Basic Books, Inc.) (A more popular science book)\
-   For more technical discussions of causality:
    -   [Holland 1986, JASA](https://doi.org/10.2307/2289064)
    -   [Heckman 2000, QJE](https://www.jstor.org/stable/2586935)
    -   Pearl, J. 2009. [*Causality*](https://doi.org/10.1017/CBO9780511803161). (Cambridge, UK: Cambridge University Press).
    -   Ding, P. [*A First Course in Causal Inference.*](https://arxiv.org/pdf/2305.18793) online.

# Do you feel like you could use more background or a refresher on the basics?

## Variables, distributions, conditional distributins and means, types of data

-   [The Effect Ch. 3: Describing Variables](https://theeffectbook.net/ch-DescribingVariables.html)
-   [The Effect Ch. 4: Describing Relationships](https://theeffectbook.net/ch-DescribingRelationships.html)

## Hypothesis testing, type I and type II errors

## Logistic Regression

[Logistic Regression Refresher](https://uc-r.github.io/logistic_regression)

# Running List of Papers that review best practices for some techniques

[Austin & Stuart (2015) for ITPW](https://pmc.ncbi.nlm.nih.gov/articles/PMC4626409/pdf/SIM-34-3661.pdf): Moving towards best practice when using inverse probability of treatment weighting (IPTW) using the propensity score to estimate causal treatment effects in observational studies.

[Kimmel et al. 2023 for power analysis and reporting for reproducibility](https://www.nature.com/articles/s41559-023-02144-3): Particularly, see suggestions in Table 1: Changes in research practices to help increase the reliability of ecological research.
