---
title: "Schedule"
---

In general, on Mondays we will have brief lectures and demonstrations in R, while on Wednesdays, we will have student-led paper discussions and/or replication exercises of published papers. In the latter half of the course, we will shift to work-shopping our own projects and discussing additional issues and considerations with applied causal inference. In this way, we will use a partially flipped classroom and strive to create a collaborative and inclusive classroom environment to discuss, ask questions, collaborate, and get feedback on your analyses.

Because this course is part of a larger, distributed graduate seminar (dgs), some lecture days will feature content and lectures from instructors from other universities who are part of this dgs.

The tentative schedule of content, subject to change based on student interests and availability of guest speakers, is as follows:

+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                 | Monday                                                                             | Wednesday                                                                                                                 | Goals/Topics                                                                                                                                                                                                                                                                                                                                                                                                                   |
+:===============:+:==================================================================================:+:=========================================================================================================================:+:==============================================================================================================================================================================================================================================================================================================================================================================================================================:+
| Week 1 (8/24)   | Course Intro                                                                       | Intro to causal inference and counterfactual causality                                                                    | • Intro to course and goals <br> • Understand students’ goals for the course <br> • Set norms and expectations <br> • Intro to concepts in causal inference and motivation for applying it to ecology and evolution <br> • Clarify causal versus other research questions and aims <br> • Brief Introduction to two main frameworks for counterfactual causality (potential outcomes and graphical causal modeling frameworks) |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 2 (8/31)   | Structural Causal Models and Directed Acyclic Graphs                               | Potential outcome framework                                                                                               | Intro to the main frameworks for counterfactual causal inference                                                                                                                                                                                                                                                                                                                                                               |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 | (Guest speaker: \[Dr. Zach Laubach\](<https://laubach.github.io>))                 |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 3 (9/7)    | Labor Day - No Class                                                               | Randomized Controlled Experiments (or RCTs) and experimental design                                                       | • Application of potential outcomes framework to RCTs <br> • Review key assumptions of RCTs <br> • Dissect experimental design with respect to assumptions required for causal inference                                                                                                                                                                                                                                       |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 4 (9/14)   | Bias and solutions in expertiments                                                 | External Validity                                                                                                         | Identify when key assumptions for causal inference are violated in experiments <br> • Critique experimental designs in ecology and identify solutions <br> • Identify solutions                                                                                                                                                                                                                                                |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | [Dr. Allison Simler-Williamson](https://www.boisestate.edu/biology/faculty-and-staff/faculty/allison-simler-williamson/)  | External Validity: Target Validity and Transportability                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 5          | Observational data and counterfactuals; Introduction to quasi-experimental methods | Creating and Analyzing DAGs                                                                                               | • Articulate how and why observational data deviates from assumptions of RCTs <br> • Understand challenges of applying causal inference to observational data, including confounding and selection bias <br> • DAGs as a tool from the graphical causal modeling framework <br> • Principles of covariate and confounder selection <br>                                                                                        |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
| (9/20)          |                                                                                    | *Due: first draft of research question, or lit review proposal, and DAG analysis*                                         | Project Workshop:                                                                                                                                                                                                                                                                                                                                                                                                              |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    |                                                                                                                           | • Students create and workshop DAGs for their own research/study systems                                                                                                                                                                                                                                                                                                                                                       |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 6 (9/28)   | Pre-regression matching                                                            | Paper discussion and replication exercise                                                                                 | • Learn pre-regression matching as a method <br> • Demo application in R <br> • See & critique how it is applied in the literature                                                                                                                                                                                                                                                                                             |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 7 (10/5)   | Difference in Difference (DiD)                                                     | Paper discussion and replication exercise                                                                                 | • Learn DiD designs, including identification assumptions and interpretation <br> • Demo application in R <br> • Compare DiD to matching and experiments <br> • See & critique how it is applied in the literature <br> • Staggered treatment timing and heterogeniety extensions in "modern DiD"                                                                                                                              |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 8 (10/12)  | Panel methods continued: Two way fixed effects, clustered designs, and extensions  | Paper discussion and replication exercise                                                                                 | • Learn within estimators (two-way fixed effects) including identification assumptions and interpretation <br> • Mundlak devices <br> • Compare panel designs with conditioning on observables designs and with random effect/mixed effect models in R and understand the differences in assumptions <br> • Compare applications in literature and the assumptions required for the conclusions drawn                          |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | OR Synthetic Control (Asia Kaiser)                                                                                        | • Learn synthetic control including identification assumptions and interpretation <br> • Compare it to other types of designs                                                                                                                                                                                                                                                                                                  |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | *Due Draft of DAG OR literature review proposal (2 page max.)*                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 9 (10/19)  | Instrumental Variables (IV)                                                        | IV Paper discussion                                                                                                       | • Learn IV as a method <br> • Demo application in R <br> • See & critique how it is applied in the literature                                                                                                                                                                                                                                                                                                                  |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 10 (10/26) | Regression Discontinuity Designs (RDD)                                             | RDD discussion and application                                                                                            | • Learn RDD as a method <br> • Demo application in R <br> • See & critique how it is applied in the literature                                                                                                                                                                                                                                                                                                                 |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 11 (11/2)  | Comparison across designs; Intro to robustness checks                              | Project work and discussions of design choices                                                                            | • Articulate, compare, and parse the assumptions, estimands, and generalizability of different designs <br> • Intro to Sensitivity Tests                                                                                                                                                                                                                                                                                       |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | *DUE: In class - brief presentation on project*                                                                           | • Make progress on project and get feedback on proposed research design and challenges so far from Laura and your classmates                                                                                                                                                                                                                                                                                                   |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 12 (11/9)  | Inference, Power, Standard Errors, Reproducibility; Randomization inference        | Heterogeniety, generalizability                                                                                           | <br> • Standard errors, power, and inference with quasi-experimental methods                                                                                                                                                                                                                                                                                                                                                   |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | Special topic: Generalizability (Guest speaker: [Dr. Becks Spake](https://www.reading.ac.uk/ecology/staff/rebecca-spake)) | • <br>Introduction to challenges with generalizability                                                                                                                                                                                                                                                                                                                                                                         |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    |                                                                                                                           | • <br> Crititically consider Generalizability, transportability, and approaches to increase them <br> • Clearly communicate the application of causal inference methods to a research question in ecology OR present a topic we did not cover as a class                                                                                                                                                                       |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 13 (11/16) | Mediation Analysis;                                                                | TBD (likely ML and causal)                                                                                                | • Introduction to mediation analysis <br> • <br> Articulate additional assumptions for mediation                                                                                                                                                                                                                                                                                                                               |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 | Sensitivity and placebo tests                                                      |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 14 (11/23) | No class                                                                           | No class                                                                                                                  | Thanksgiving Break                                                                                                                                                                                                                                                                                                                                                                                                             |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week 15 (11/30) | *Project presentations*                                                            | *Project presentations*                                                                                                   | • Clearly communicate the application of causal inference methods to a research question in ecology OR present a review on a topic we did not cover as a class                                                                                                                                                                                                                                                                 |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 | Group 1                                                                            | Group 2                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    |                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                 |                                                                                    | *Final Write up due by midnight on Dec 6th by email*                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------+------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

# Potential additional topics/units to be voted on by the class:

### Generalizability in experimental and observational studies

1)  [Korell et al. 2019](https://doi.org/10.1111/gcb.14797)
2)  [Spake et al. 2022](https://www.nature.com/articles/s41559-022-01891-z)
3)  [Spake et al. 2021](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13641)

### Machine Learning and Causal Inference

### Heterogeneous treatment effects and conditional average effects

e.g. Causal Forests

### Deeper dive into Mechanisms and Mediation analysis

### Deeper dive into Sensitivity Tests

### Replication/Reproducibility/Pre-registration

e.g. [Kimmel et al. 2023 Empirical evidence of widespread exaggeration bias and selective reporting in ecology](https://www.nature.com/articles/s41559-023-02144-3)
